//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.1
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AionLogAnalyzer {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SkillNameList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkillNameList() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AionLogAnalyzer.SkillNameList", typeof(SkillNameList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   격노 폭발,분쇄 파동,신성력 폭발,분노의 일격,파열의 일격,칼날 날리기,내려찍기,공중 결박,몸통 강타,쇠약의 맹타,강제 낙하,충격 파동,복수의 강타,도약 찍기,광폭 파동,강제 결박,무모한 일격,흡혈 파동,압력 파동,칼날 연사,칼날 화무,분노의 파동,성문 파괴,검기 투척,지진 파동,흡혈 찍기,파괴의 일격,노련한 반격,예리한 일격,검기 파열,살기 파열,파멸의 맹타,절단의 일격,검기 파동,살기 파동,최후의 일격,발목 베기,회전 일격,분노 폭발,격파의 일격,유린의 맹타,흡혈의 검,고갈의 파동,흡수 파동,몸통 타격,마력 방어,반격 준비,용참 파동,광폭 찍기,발목 묶기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 검성 {
            get {
                return ResourceManager.GetString("검성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변신: 라이칸,변신: 크랄,올가미 화살,저격,경계의 눈,조준 화살,아교 덫,중독의 덫,연사,집중의 눈,강습 화살,수면 화살,화살 폭우,독 화살,퇴보 베기,침묵 화살,강화의 눈,파열 화살,폭발의 덫,폭발의 덫,축복의 활,바람의 활력,나선 화살,올가미 덫,투시의 덫,파멸의 덫,공중 난사,투시의 눈,대자연의 숨결,집중 속사,송곳 화살,둔화의 덫,결박의 덫,저격 자세,항마의 화살,화살 폭풍,흙먼지 덫,충격 화살,족쇄 화살,공격의 눈,그리폰 화살,콘도르 화살,속사의 눈,질풍 화살,바람의 질주,폭발 화살,사냥꾼의 결의,날개 치료,저항의 결의,퇴각 베기,흡수의 결의,바이젤의 화살,트리니엘의 화살,그리포닉스 화살,콘시어드 화살,광풍 화살,광포의 화살,수면의 덫,작렬의 덫,화살 강화,탈취 화살,시무르그 부르기,필중의 화살,번개 화살,고통의 화살,격습 화살,비명 속사,순간 속보,최후의 강습,충격의 덫,폭풍 기뢰,봉인 화살과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 궁성 {
            get {
                return ResourceManager.GetString("궁성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감도 증폭,갑옷 파괴,강격,공중 발포,급소 찌르기,냉각파,도발풍,도약 격파,마력 흡수,반격 발포,반격타,분쇄파,비행 발포,비행 진격타,신룡포,약점 찌르기,양손 가격,연격,연속 발포,연타,올려치기,이디움 광선,이디움 주먹,이디움 채찍,이디움 포격,일격,전기 속박,전기 올가미,전기 충격,진격타,침묵 강타,파쇄 강타,폭풍 연타,합장,화염 격파,화염 발포,화염 방사,흡혈파과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 기갑성 {
            get {
                return ResourceManager.GetString("기갑성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수면: 허수아비,신성한 주문,혼신의 주문,수면,작렬,시공의 뒤틀림,불꽃 작살,대지의 로브,겨울의 속박,지연 폭발,냉기 파동,저주: 나무,루미엘의 지혜,시공의 회랑,불꽃의 로브,빙판,평화의 은혜,냉기 소환,철갑화의 은혜,공중 속박,지켈의 지혜,쇠약의 저주,투시의 은혜,바람의 칼날,화염 발사,수면 구름,냉기의 로브,지옥의 화염,극기,화염 폭발,화염 융해,나락,바이젤의 지혜,영혼 흡수,원기 흡수,영혼 동결,화염의 원무,신성 폭발,암흑 폭발,혹한,결빙,태풍 소환,강화의 은혜,신속의 은혜,얼음 작살,환영의 회오리,환영,암석 소환,집중의 기원,유성 강타,단절의 결계,시공 도약,화산 대폭발,용암 태풍,수면 폭풍,화염 난무,카이시넬의 진노,루미엘의 진노,화산 폭발,용암 해일,마력의 얼음칼,원소 결계,낙뢰,저주: 고목,생기 교환,마력 증폭,빙설의 갑주,빙하 강타,바람 화살,불꽃의 창,수면 해제,연쇄 보호막,지연 폭염,마력의 염화,숙면 유도,화상,바람의 창과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 마도성 {
            get {
                return ResourceManager.GetString("마도성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미간 사격,견제 연사,약점 사격,연속 속사,강탄 사격,절혼 사격,절혼 연사,절혼 속사,절혼 사격,봉인 사격,신속 연사,회복 연사,속박의 포탄,나락의 포탄,위기 탈출,탈취의 탄환,마력의 숨결,마력의 은혜,침묵의 탄환,빙결포,화마포,흡혼 사격,혼령포,절혼포,속박의 포탄,충격포,방사 포격,균열의 포탄,미간 정조준,마력탄 충전,마력탄 강화,급소 관통,신속 연사,마력의 약속과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 사격성 {
            get {
                return ResourceManager.GetString("사격성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암흑의 일격,신성한 일격,진격 베기,살의 극대화,질주,문양 각인,문양 폭발,독 바르기,맹수의 포효,신속의 계약,연쇄 문양 각인,회피의 계약,빈틈 노리기,고대 문양 각인,암습,회오리 베기,공중 포박,극약 바르기,문양 파쇄,맹수의 뒷발차기,암살,명중의 서약,그림자 망토,고갈의 문양 폭발,원거리 문양 각인,배후 강타,연막탄,낙하,분노의 눈,필중의 문양 폭발,나선 베기,그림자 분신,맹수의 후려치기,경계 자세,기습 자세,맹수의 송곳니,표창 투척,그림자 보행,맹수의 상흔,쾌속 베기,폭약 바르기,번개 베기,단검 투척,각오,연쇄 화인,빛의 문양 폭발,어둠의 문양 파열,바이젤의 비수,트리니엘의 비수,천공의 문양 폭발,나락의 문양 파열,연쇄 문양 폭발,기습 베기,연속 회피,섬광 폭발,육감 극대화,폭풍 베기,맹독의 기습,강습 자세,침묵의 문양 폭발,혼절의 칼날,후면 베기,도주 자세,후면 타격,배후 습격,후면 강타,그림자 낙하과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 살성 {
            get {
                return ResourceManager.GetString("살성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   신성한 응징,암흑의 응징,방패 강타,주신의 갑옷,방패 찍기,도발의 맹타,섬광 베기,필사의 일격,격앙,보호의 방패,포획,철벽 방어,응징의 일격,연속 난타,돌격,도발의 포효,무기력의 맹타,분노 유발,징벌,치유의 손길,방패 돌격,둔화의 맹타,모욕의 포효,균형의 갑옷,발목 강타,전우 보호,심판,나포,천둥 베기,성문 파괴,이중 갑옷,혈관 베기,방패 휘두르기,회생의 권능,차단의 갑옷,기사회생,정신 파괴,마력 강타,비호의 갑옷,쾌속의 방패,전율의 포효,생명력 충만,주신의 징벌,빛의 징벌,어둠의 징벌,견고한 방패,파괴의 기합,사신의 징벌,네자칸의 방패,지켈의 방패,방패 타격,위협,속박의 파동,생포,반격 방어,극한의 맹타,주신의 보호,파멸의 방패,집중 나포,혈검 베기,회생의 스킬,공수 전환,격려의 포효,위협의 파장,처단의 일격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 수호성 {
            get {
                return ResourceManager.GetString("수호성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   냉기의 화음,불꽃의 화음,대지의 화음,바람의 화음,영혼의 화음,절혼의 화음,멸혼의 화음,침묵의 화음,온유한 울림,온후한 울림,온화한 울림,청초한 울림,청아한 울림,청정한 울림,돌풍 광시곡,해일의 광시곡,감동의 선율,충격의 파열음,광대 무곡,재생의 선율,천상의 진혼곡,망각의 광시곡,숨막히는 파열음,벌들의 행진곡,평화 야상곡,철갑의 선율,눈꽃의 선율,면죄의 선율,극기의 선율,치유 변주곡,평온 변주곡,치유 주법,불협화음,용기의 선율,마비의 메아리,모스키 광시곡,증폭 주법,날카로운 마찰음,타격의 메아리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 음유성 {
            get {
                return ResourceManager.GetString("음유성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정령 강화: 빛의 갑옷,정령 강화: 어둠의 갑옷,정령 강화: 회복,정령 강화: 치유,정령 강화: 질주,정령 강화: 원소의 갑주,정령 강화: 강화의 갑주,소환: 불의 정령,소환: 바람의 정령,소환: 땅의 정령,소환: 물의 정령,소환: 용암의 정령,소환: 태풍의 정령,소환: 원소의 기운,소환: 불의 기운,소환: 바람의 기운,소환: 땅의 기운,소환: 물의 기운,소환: 회오리의 기운,소환: 파티원,명령: 뇌전 발톱,명령: 위협의 기세,명령: 분노의 기세,명령: 부식,명령: 교란,명령: 수호의 장벽,명령: 기폭의 발톱,명령: 희생,명령: 자폭,명령: 전소,명령: 폭발,명령: 파멸의 공세,명령: 대역,명령: 정령의 가호,명령: 최면,명령: 원소 폭풍,명령: 보호,명령: 압박의 기세,무기력의 구속,대지의 사슬,마법 해제,원소 보충,강철 보호막,육체 구속,생기 흡수,진공 폭발,대지 진동,정령의 희생,광역 침식,마법 연소,마법 차단,영혼의 절규: 삼,영혼의 절규,복종의 수인,불길의 축복,마법 강탈,정령 흡수,저항의 계약[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 정령성 {
            get {
                return ResourceManager.GetString("정령성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대지의 응보,뇌전,재생의 빛,구원,어둠의 가호,정화,진정,심판의 번개,소환: 신성한 수정,소환: 신성한 기운,치유의 은총,청명,고행,섬광,주신의 은총,벼락,치유의 바람,환생,방전,따뜻한 가호,차가운 가호,쾌유의 섬광,대지의 분노,회복 차단,필사의 교환,가시 보호막,쾌유의 빛,면죄,신속의 기도,응징,소환 부활,집중의 기도,부활의 은총,치유의 보호막,쾌유의 광휘,파멸의 목소리,응징의 번개,징벌의 번개,정화의 광휘,유스티엘의 빛,마르쿠탄의 빛,안정,재생의 광휘,기억 분쇄,고통의 연쇄,환생의 손길,회복의 가호,비상의 광휘,교감 치유,방호의 장막,유스티엘의 광휘,마르쿠탄의 광휘,정화의 물결,소환: 고결한 기운,찬란한 가호,증폭의 기도,소환: 치유의 기운,약화의 낙인,뇌우,대지의 징벌,불사의 장막,생명의 권능,벽력,대지의 격노,권능 폭발,전력 질주,치유의 섬광,권능 부여,치유의 광휘,응보의 번개,고결한 기운과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 치유성 {
            get {
                return ResourceManager.GetString("치유성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   승리의 진언,유성격,유스티엘의 보호,마르쿠탄의 보호,격파쇄,소생의 주문,방패의 진언,대지의 약속,마력의 진언,질주의 진언,백열격,흡수의 주문,격노의 주문,보호진,집중 방어,공명쇄,소생의 진언,총명의 진언,열파격,오드의 약속,수호의 주문,파열격,결박의 주문,질풍의 주문,벽력쇄,정확의 진언,생명의 주문,공명 연무,신속의 주문,보호의 진언,천벌의 낙인,유수격,고취의 주문,관통쇄,타격쇄,암격쇄,차단의 주문,결계의 주문,쾌유의 주문,십자 방어,기력 재생,바람의 축복,마력 회복,수호의 축복,쾌속의 주문,필멸 강타,강격쇄,속박의 주문,차단의 장막,결계의 장막,파산격,불패의 진언,육체 강화,파동격,쾌유의 손길,진동쇄,행운의 진언,충격쇄,분쇄격,철벽의 주문,질주의 기운,연속 격파,질주 격려,분열격,시공 탈출,바람의 진언,절명타,비뢰격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 호법성 {
            get {
                return ResourceManager.GetString("호법성", resourceCulture);
            }
        }
    }
}
